---
abstract: 'Pluggable Data Decoder'
author:
  - 'Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Decode
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  Encode::Guess: 0
  Exception::Class: 0
  HTML::Parser: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  MooseX::NonMoose: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00007_01
